// Ported verbatim from the Corpus monorepo (Apache-2.0 relicense by the author).
/** Common NAICS codes (Census 2022). Seed set — expand from the full Census file later. */
export interface NaicsEntry { code: string; title: string; }
export const NAICS_CODES: NaicsEntry[] = [
  { code: "541511", title: "Custom Computer Programming Services" },
  { code: "541512", title: "Computer Systems Design Services" },
  { code: "541330", title: "Engineering Services" },
  { code: "541110", title: "Offices of Lawyers" },
  { code: "541211", title: "Offices of Certified Public Accountants" },
  { code: "541611", title: "Administrative Management and General Management Consulting Services" },
  { code: "541810", title: "Advertising Agencies" },
  { code: "541921", title: "Photography Studios, Portrait" },
  { code: "722511", title: "Full-Service Restaurants" },
  { code: "722513", title: "Limited-Service Restaurants" },
  { code: "722515", title: "Snack and Nonalcoholic Beverage Bars" },
  { code: "445110", title: "Supermarkets and Other Grocery Retailers" },
  { code: "448140", title: "Family Clothing Stores" },
  { code: "453110", title: "Florists" },
  { code: "454110", title: "Electronic Shopping and Mail-Order Houses" },
  { code: "236118", title: "Residential Remodelers" },
  { code: "238220", title: "Plumbing, Heating, and Air-Conditioning Contractors" },
  { code: "238210", title: "Electrical Contractors and Other Wiring Installation Contractors" },
  { code: "811111", title: "General Automotive Repair" },
  { code: "812112", title: "Beauty Salons" },
  { code: "812113", title: "Nail Salons" },
  { code: "621210", title: "Offices of Dentists" },
  { code: "621111", title: "Offices of Physicians (except Mental Health Specialists)" },
  { code: "611699", title: "All Other Miscellaneous Schools and Instruction" },
  { code: "624410", title: "Child Day Care Services" },
  { code: "531210", title: "Offices of Real Estate Agents and Brokers" },
  { code: "523930", title: "Investment Advice" },
  { code: "522110", title: "Commercial Banking" },
  { code: "311811", title: "Retail Bakeries" },
  { code: "312120", title: "Breweries" },
  { code: "312140", title: "Distilleries" },
  { code: "424490", title: "Other Grocery and Related Products Merchant Wholesalers" },
  { code: "484110", title: "General Freight Trucking, Local" },
  { code: "485310", title: "Taxi and Ride-Hailing Services" },
  { code: "713940", title: "Fitness and Recreational Sports Centers" },
  { code: "711130", title: "Musical Groups and Artists" },
  { code: "541430", title: "Graphic Design Services" },
  { code: "561730", title: "Landscaping Services" },
  { code: "561720", title: "Janitorial Services" },
  { code: "813110", title: "Religious Organizations" },
  { code: "813211", title: "Grantmaking Foundations" },
  { code: "813311", title: "Human Rights Organizations" },
  { code: "813410", title: "Civic and Social Organizations" },
  { code: "999999", title: "Unclassified / Not Yet Determined" },
];
